- 👋 Hi, I’m @tantanpog
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
tantanpog/tantanpog is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
Thx pa sana nga sabi mo sa bahay na agko ako mga ising iwag mo saka ika na sya sa mga paninda
